version: "3.6"
services:
  server:
    build: .
    volumes:
      - ".:/app"
      - "assets_node_modules:/app/assets/node_modules"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: "iex -S mix phx.server"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres/cryptobot_dev"
      TEST_DATABASE_URL: "postgres://postgres:postgres@postgres/cryptobot_test"
      ACCESS_TOKEN: "<FacebookToken>"

  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db_data:
  assets_node_modules:
